### ISSUE TITLE
[Feat] 습관방 시작 서버 연결

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#109]
## 📌  Issue

대기방에서 습관방 시작 서버 연결

## 📝  To-do

- [ ] 대기방 하단 버튼 이름 변경
- [ ] 토스트메세지 위치 변경
- [ ] 습관방 서버 연결
- [ ] 툴팁을 할까.... 말까......
- [ ] 홈으로 화면 전환
