### ISSUE TITLE
[Fix] 홈 엠티뷰 스크롤 막기

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#139]
## 📌  Issue

홈 엠티뷰 스크롤 막기

## 📝  To-do

- [x] 막기 전에 카카오 로그인해서 계정 맹글기
- [x] 홈 엠티뷰 스크롤 막기
- [x] 홈 엠티뷰 레이아웃 수정
- [x] 멘트 확인
