### ISSUE TITLE
[Fix] 습관방 멘트, 상태바, 상태 스티커 수정하기

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#165]
## 📌  Issue

- 습관방 인증가능할때 멘트 수정
- 상태바 하얀색으로 등장하게 수정
- 상태 스티커 수정하기
- 66일일때 오늘의 인증 버튼 비활성화
## 📝  To-do

- [x] 습관방 인증가능할때 멘트 수정
- [x] 상태바 하얀색으로 등장하게 수정
- [x] 상태 스티커 수정하기
- [x] 66일일때 오늘의 인증 버튼 비활성화
