### ISSUE TITLE
[Add] 이미지 에셋 추가(2차)

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#18]
## 📌  Issue

- 이미지 에셋 추가! 2차~!

## 📝  To-do

- [x]  소셜로그인 버튼 이미지 에셋
- [x]  프로필 사진 설정 시 뒤쪽의 스파크로고 에셋
- [x]  보관함 테두리 에셋
- [x]  icHeart 네이밍
- [x]  탭바에 들어가는 활성화된 아이콘과 비활성화된 아이콘 에셋
- [x]  습관방 상단의 스파크플레이크와 배경을 포함한 에셋
- [x]  보관함 플레이크 영역 및 그라데이션
- [x]  메인 티켓 수정
