### ISSUE TITLE
[Feat] 타이머 + 사진 습관 인증하기뷰 오른쪽 상단 X버튼 추가

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#183]
## 📌  Issue

타이머 + 사진 습관 인증하기뷰 오른쪽 상단 X버튼 추가

## 📝  To-do

- [x] 오른쪽 상단 X 버튼 추가
- [x] 화면 전환 연결
- [x] 다이얼로그
- [x] 타이머 실행 후 종료시 다이얼로그
