### ISSUE TITLE
[Feat] 보관함 뷰 레이아웃

### ISSUE THREAD

**Issue by L-j-h-c** [TeamSparker/Spark-iOS#24]
## 📌  Issue

보관함 레이아웃 구현

## 📝  To-do

- [x] Carousel Layout 생성 및 레이아웃 구현
- [x] FirstCarouselCVC 생성 및 레이아웃 구현
- [x] SecondCarouselCVC 생성 및 레이아웃 구현
- [x] ThirdCarouseCVC 생성 및 레이아웃 구현
- [ ] 더미데이터 추가
- [ ] 무한스크롤 로직 연결
