### ISSUE TITLE
[Fix] 나의 목표 작성 뷰 디테일 수정 및 텍스트필드 extension 분리

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#241]
## 📌  Issue

나의 목표 작성 뷰 QA 및 텍스트필드 extension 분리

## 📝  To-do

<img width="284" alt="스크린샷 2022-02-10 오전 12 52 16" src="https://user-images.githubusercontent.com/81167570/153237876-62cfbe7d-1260-483e-896e-5a7a3251394b.png">

- [x] 상단 문구에 작은 따옴표 추가 
- [x] 텍스트필드 선택시 활성화 
- [x] 텍스트필드 extensioin 분리 는 내 오만이었나
