### ISSUE TITLE
[Fix] 대기방 뷰 디테일 수정

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#244]
## 📌  Issue

대기방 관련 QA 반영 수정

## 📝  To-do

- [x] 습관방 이름 - 코드복사 사이 간격 조정
- [x] 구분선 굵기 색깔 진하게
- [x] 새로고침 모션 후 위치 요상한 문제 해결
<img width="280" alt="스크린샷 2022-02-10 오후 1 34 33" src="https://user-images.githubusercontent.com/81167570/153337769-3955cf85-a11b-469d-a43a-18c96225d3fa.png">
