### ISSUE TITLE
[Fix] 보관함 뷰, 인증사진 모아보기 뷰 관련 디자인 QA

### ISSUE THREAD

**Issue by L-j-h-c** [TeamSparker/Spark-iOS#246]
## 📌  Issue

보관함 뷰 관련 디자인 QA 진행하겠습니다.

## 📝  To-do

- [ ] 보관함 습관 카드 라인 안쪽으로 사진 넣어주기
- [ ] 보관함 텍스트 간격 조정하기
- [ ] 보관함 empty뷰가 뜨지 않는 문제 분기처리 관련 수정
- [ ] 보관함과 인증사진 모아보기 스파크 아이콘 컬러 spark_gray로 수정
- [ ] 인증사진 모아보기 격자 컬러 dark gray에 20%로 수정
