### ISSUE TITLE
[Feat] 대기방 레이아웃 구현

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#26]
## 📌  Issue

대기방 레이아웃 구현

## 📝  To-do

- [x] WaitingVC 레이아웃 
- [x] WatingFriendCVC 
- [x] 에셋 추가
- [x] 에셋 적용
- [x] UILabel+extension 추가
- [x] 더미데이터 추가 + 연결
- [x] 코드 복사 기능
- [x] 토스트메세지
