### ISSUE TITLE
[Fix] 엠티뷰 레이아웃 수정

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#265]
## 📌  Issue

엠티뷰 레이아웃 수정

## 📝  To-do

- [x] 홈
- [x] 피드
- [x] 보관함

- [ ] 보관함 상단 레이아웃 수정
- [ ] 홈 CVC 말고 그냥 엠티뷰 바로 때려박기
- [ ] 피드도 CVC 말고 그냥 엠티뷰 박기
