### ISSUE TITLE
[Feat] 커스템 네비게이션바 적용

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#288]
## 📌  Issue

- 커스텀 네비게이션바 적용
## 📝  To-do

- [x] 홈(우측두개)
- [x] 홈 -> 대기방(좌우측)
- [x] 방생성 -> 대기방(좌우측)
- [x] 습관선택(CreateAuthVC)
- [x] 습관방(좌우측)
- [x] 습관방 생성(좌측)
- [x] 인증하기 타이머(좌우측)
- [x] 보관함 인증사진 모아보기(좌측)
