### ISSUE TITLE
[Feat] 대기방 더보기(방삭제, 방나가기) 구현

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#305]
## 🛠 Issue

대기방 더보기 구현

## 📝 To-do

- [x] 액션시트 분기처리
- [x] 대기방 삭제 `방장` 서버 연결
- [x] 대기방 나가기 `참여자` 서버 연결
- [ ] 습관방 나가기 서버 연결
