### ISSUE TITLE
[Feat] 마이페이지 프로필 수정 서버통신 연결 및 뷰 구현

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#342]
## 🛠 Issue

- 프로필 수정 서버통신 및 뷰 구현
## 📝 To-do

- [x] 마이페이지에서 프로필과 닉네임을 가져오기 위해서 서버통신
- [x] 프로필 수정 뷰 구현 및 서버통신 연결
- [x] 프로필 수정 후 마이페이지에 반영
- [x] 다이얼로그 붙이기
