### ISSUE TITLE
[Feat] 알림 뷰 서버 연결

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#364]
## 🛠 Issue

알림뷰 서버 연결
<img width="671" alt="스크린샷 2022-03-10 오후 2 03 55" src="https://user-images.githubusercontent.com/81167570/157593279-ceb8639c-c2fc-4271-9ac4-b4dbc6ae29b3.png">

## 📝 To-do

- [x] 활동 알림 조회
- [x] 활동 알림 읽음 처리
- [x] 서비스 알림 조회
- [x] 서비스 알림 읽음 처리
- [x] 알림 조회 시, 빨콩 처리
- [x] 추가 UI 작업
