### ISSUE TITLE
[Fix] 인증사진 모아보기 뷰 레이아웃 수정

### ISSUE THREAD

**Issue by L-j-h-c** [TeamSparker/Spark-iOS#47]
## 📌  Issue

인증사진 모아보기 뷰 컬렉션뷰 레이아웃 수정

## 📝  To-do

- [x] 컬렉션뷰 탑 인셋 주기
- [x] 인디케이터 위치 고려하여 컬렉션뷰 슈퍼뷰에 밀착시키기
- [x] 셀사이즈 리턴값 재설정하기
