### ISSUE TITLE
[Docs] 리드미 수정

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#5]
## 📌  Issue
리드미 작성

## 📝  To-do

- [x] 간단한 프로젝트 설명
- [x] 참여 구성원
- [x] Coding Convention
- [x] Git branch 전략
- [x] 프로젝트 폴더링 Convention
