### ISSUE TITLE
[Fix] 알림뷰 버튼 왔다갔다 할 경우 비정상 종료 문제 해결

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#525]
## 🛠 Issue

알림뷰 버튼 왔다갔다 할 경우 비정상 종료 문제 해결

## 📝 To-do

- [x] ~~서버통신 completion handler에서 처리~~
- [x] rxswift, rxcocoa 설치 
- [x] debounce / throttle로 처리
