### ISSUE TITLE
[Feat] 방생성 플로우 화면 전환 연결

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#59]
## 📌  Issue

`홈 -> 방생성 -> 대기방 ` 플로우 화면 전환 연결

## 📝  To-do

- [x] 네비게이션 컨트롤러 적용
- [x] 화면 전환
- [x] 대기방 네비게이션 바 추가
- [x] 대기방 습관 인증 방식 반영
