### ISSUE TITLE
[Bug] 습관방 한 개일 때 삭제(실패, 방 삭제, 나가기) 후, 새로고침 후 사라지지 않는 버그

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#618]
## 🛠 Issue

- 실패방이 한개일 때 확인 후 엠티뷰가 등장해야하지만 사라지지 않는 버그 확인
<img src="https://user-images.githubusercontent.com/69136340/168265122-843ae833-0e6d-40b9-81a6-f0a55be44546.mov" width ="250">

## 📝 To-do

- [x] 서버문제인지 로그를 확인해봐야할 것 같다.
![스크린샷 2022-05-13 오후 8 17 44](https://user-images.githubusercontent.com/69136340/168272633-d247449b-b19c-4888-afdc-6fee9c841879.png)
**->**
- [x] 빈배열이 넘어오는데 한개를 보여주고 있다.(대기방을 나갈때도 동일해서 습관방 리스트가 1개일경우에 해당하는 버그라고 판단하고 이슈 제목 수정)
**->**
- [x] `if self.newHabitRooms.count == 0, self.habitRooms.count == 0 {` 조건문의 조건 수정.
