### ISSUE TITLE
[Fix] 기기 대응 레이아웃 수정

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#63]
## 📌  Issue

se2, 13Pro, 13mini
기기 대응시 레이아웃 깨지는 부분 수정

## 📝  To-do

- [x] 방생성 플로우 CreateRoomVC
- [x] 방생성 플로우 CreateAuthVC
- [x] 목표 작성 GoalWritingVC
- [x] 타이머 AuthTimerVC
- [x] 사진인증 AuthPhotoVC
- [x] 피드 FeedVC
- [x] 프로필설정 ProfileSetting
