### ISSUE TITLE
[Chore] 서버 호스트 주소 및 키 값 삭제

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#644]
## 🛠 Issue

- 테스트 서버 사용할 수 있도록 환경 설정
- 기존의 서버 주소 삭제
- 카카오 키 값 삭제
## 📝 To-do

> 현재까지 생각해본 방법
- [x] build configuration 에 따른 scheme 생성
    - [iOS 프로젝트 배포 환경별 build 세팅하기](https://trend21c.tistory.com/2103)
    - [[iOS - swift] iOS 프로젝트 배포 환경별 build 세팅, Build Scheme 세팅 (단일타겟, xcconfig)](https://ios-development.tistory.com/428)
    - [[iOS - swift] iOS 프로젝트 배포 환경별 build 세팅(info.plist 방법, 단일 타겟), debug / alpha / beta / release](https://ios-development.tistory.com/278)
- [x] configuration 파일에 키, 주소를 두고 .gitignore 에 추가해서 제외시키기
    - [정대리 - app key 숨기기](https://www.notion.so/iOS-App-Key-01181926407947359140c87bd8af3d8d)

**Comment by hyun99999** [comment]
- [ ] key 숨기기 좀 더 찾아보기
- [ ] fastlane 으로 테스트 플라이트 자동 배포
