### ISSUE TITLE
[Fix] HabitRoomDetail 모델 수정 및 생명 화면 전환 연결

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#655]
## 🛠 Issue

HabitRoomDetail 모델 수정 및 생명 화면 전환 연결
- 습관방에서 수정이 필요한 부분, 생명 타임라인 뷰와 연결된 부분 수정하겠습니다
- 그 업그레이드 팝업 작업에서두 HabitRoomDetail 수정이 필요할거라 아래 적어둔거만 먼저 쇽샥 해서 올려둘게여? (근데 제가 좀 늦는거같으면 먼저 그냥 각자 .. 하고 합치지 뭐...)

## 📝 To-do

- [x] HabitRoomDetail 모델 수정
- [x] lifeDeductionCount랑 연결된 부분 다 삭제
- [x] 습관방 생명 빨콩 에셋 추가
- [x] 습관방 생명 빨콩 레이아웃 수정
- [x] 습관방 생명 -> 생명 타임라인 화면 전환
