### ISSUE TITLE
[Feat] 스톱워치 + 사진 인증하기 중 사진인증 뷰 구현

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#68]
## 📌  Issue

스톱워치 + 사진 인증하기 중 사진인증 뷰 구현

## 📝  To-do

- [x] 풀받아서 진행
- [x] UI 함수 분리
- [x] 사진 이미지 뒤에 투명 uiview 추가
- [x] 스톱워치 -> 사진 인증 플로우 연결
