### ISSUE TITLE
[Fix] 뷰 디테일 수정

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#72]
## 📌  Issue

뷰 디테일을 모아다가 수정하겠슴니다.

## 📝  To-do

- [x] 대기방 refresh 버튼 클릭시 회전 애니메이션
- [x] 대기방 토스트메세지 위치 내리기
- [x] 피드뷰 하트 애니메이션
- [x] 타이머 단위 수정
- [x] 타이머 분기처리
- [x] 사진 업로드 하단 버튼 플로우, 멘트 변경
- [x] 피드뷰 한 번에 7-10개씩
- [x] 하단 버튼 전부 safearea로부터 20으로 수정 (`make.bottom.equalTo(view.safeAreaLayoutGuide).inset(10)` -> `20`)
- [ ] 뷰 멘트 전체 확인
