### ISSUE TITLE
[Feat] 홈뷰 습관방 조회 서버 적용

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#83]
## 📌  Issue

- 홈뷰 티켓 이미지슬라이싱 구현하기
- 홈뷰 서버 붙이기
- 대기방, 습관방 로직

## 📝  To-do

- [x] 홈뷰 티켓 이미지 슬라이싱 구현
- [x] 홈뷰 서버 붙이기
- [x] 대기방, 습관방 로직
